title: "Synthetika"
description: "AI, Hacking, Discussions"
theme: minima
url: "https://synthetika.github.io"
sass:
  style: compressed
# Which pages appear in the top menu bar
header_pages:
  - index.md      # Home
  - about.md      # About
  - projects.md   # Projects
  - contact.md    # Contact
